<?php
/**
 * 
 * Code skeleton generated by dia-uml2php5 plugin
 * written by KDO kdo@zpmag.com
 */

class News {

	/**
	 * 
	 * @var array
	 * @access protected
	 */
	protected  $erreurs;

	/**
	 * 
	 * @var int
	 * @access protected
	 */
	protected  $id;

	/**
	 * 
	 * @var string
	 * @access protected
	 */
	protected  $auteur;

	/**
	 * 
	 * @var string
	 * @access protected
	 */
	protected  $titre;

	/**
	 * 
	 * @var string
	 * @access protected
	 */
	protected  $contenu;

	/**
	 * 
	 * @var string
	 * @access protected
	 */
	protected  $dateAjout;

	/**
	 * 
	 * @var string
	 * @access protected
	 */
	protected  $dateModif;


	/**
	 * @access public
	 * @param array $valeurs 
	 * @return void
	 */

	public final  function __construct($valeurs = array()) {

	}


	/**
	 * @access public
	 * @param array $donnees 
	 * @return void
	 */

	public final  function hydrare($donnees) {

	}


	/**
	 * @access public
	 * @return bool const
	 */

	public final  function isNew() {

	}


	/**
	 * @access public
	 * @return bool const
	 */

	public final  function isValid() {

	}


	/**
	 * @access public
	 * @param int $id 
	 * @return void
	 */

	public final  function setId($id) {

	}


	/**
	 * @access public
	 * @param string $auteur 
	 * @return void
	 */

	public final  function setAuteur($auteur) {

	}


}
?>